yolo_model:

  config_file:
    name: yolov3-tiny3.cfg
  weight_file:
    name: yolov3-tiny3.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - prohibitory
      - danger
      - mandatory
      - other
